### ISSUE TITLE
Facebook messages not appear on Rocket Chat Livechat

### ISSUE THREAD

**Issue by vizarch** [RocketChat/Rocket.Chat.Livechat#322]
- I configured Omni Channel.
- I have API key and secret, logged facebook account. It appears in Livechat configurations with little slider (green color) like there https://rocket.chat/docs/administrator-guides/livechat/omnichannel-integration/

But If I send message on facebook to my funpage it doesnt appear on Rocket. 
In logs there is only:

lis 06 08:27:25 HOSTNAME rocket[13954]: === UnHandledPromiseRejection ===
lis 06 08:27:25 HOSTNAME rocket[13954]: TypeError: Cannot read property 'department' of undefined
lis 06 08:27:25 HOSTNAME rocket[13954]:     at Promise.asyncApply (app/livechat/server/lib/Livechat.js:118:25)
lis 06 08:27:25 HOSTNAME rocket[13954]:     at /home/rocket/app/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
lis 06 08:27:25 HOSTNAME rocket[13954]:  => awaited here:
lis 06 08:27:25 HOSTNAME rocket[13954]:     at Function.Promise.await (/home/rocket/app/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/pr
lis 06 08:27:25 HOSTNAME rocket[13954]:     at Promise.asyncApply (app/livechat/server/lib/Livechat.js:143:9)
lis 06 08:27:25 HOSTNAME rocket[13954]:     at /home/rocket/app/rocketchat/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
lis 06 08:27:25 HOSTNAME rocket[13954]: ---------------------------------
lis 06 08:27:25 HOSTNAME rocket[13954]: Errors like this can cause oplog processing errors.
lis 06 08:27:25 HOSTNAME rocket[13954]: Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
lis 06 08:27:25 HOSTNAME rocket[13954]: Future node.js versions will automatically exit the process

But im not sure that it's connected with this facebook problem.
How can I increase logging level?

**Comment by vizarch** [comment]
never mind :D its working. I had to wait few hours to success.
