### ISSUE TITLE
Node-gyp rebuild error, binding.gyp not found!

### ISSUE THREAD

**Issue by sanyamdogra** [RocketChat/Rocket.Chat.Livechat#379]
While setting up `Rocket.Chat.Livechat` I found an issue related to `node-gyp`.
* OS - System Linux 4.4.0-18362-Microsoft
* `Node` - 10.16.3
* `node-gyp` - 3.8.0

Issue might not be with Rocket chat but with node-gyp.
Ref- 
* https://github.com/nodejs/node-gyp/issues/1743
* https://stackoverflow.com/questions/42638918/cannot-npm-install-due-to-node-gyp-binding-gyp-not-found

###  Logs

sanyam@DESKTOP-8107IOU:/mnt/d/Projects/gsoc/rocketchat/Rocket.Chat.Livechat$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.16.3 | linux | x64
gyp info find Python using Python version 3.6.7 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [ '/mnt/c/Users/sanya/AppData/Roaming/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/d/Projects/gsoc/rocketchat/Rocket.Chat.Livechat/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/c/Users/sanya/AppData/Roaming/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/sanyam/.cache/node-gyp/10.16.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/sanyam/.cache/node-gyp/10.16.3',
gyp info spawn args   '-Dnode_gyp_dir=/mnt/c/Users/sanya/AppData/Roaming/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/sanyam/.cache/node-gyp/10.16.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/mnt/d/Projects/gsoc/rocketchat/Rocket.Chat.Livechat',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /mnt/d/Projects/gsoc/rocketchat/Rocket.Chat.Livechat) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/mnt/c/Users/sanya/AppData/Roaming/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/bin/node" "/mnt/c/Users/sanya/AppData/Roaming/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/d/Projects/gsoc/rocketchat/Rocket.Chat.Livechat
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

**Comment by sanyamdogra** [comment]
A workaround to complete my installation successfully was to a `binding.gyp` file with the content below in `Rocket.Chat.Livechat/` :

`
{
"targets": [
{
"target_name": "binding",
"sources": [ "build/Release/binding.node" ]
}
]
}
`
