### ISSUE TITLE
Omnichannel/Livechat > Facebook Messenger Integration Error (API: subscribed_fields)

### ISSUE THREAD

**Issue by jersoncristobal** [RocketChat/Rocket.Chat.Livechat#534]
### Description:
Facebook Messenger omnichannel/livechat integration not working

### Steps to reproduce:
1. Under Main Menu>Administration>Settings>Omnichannel>Facebook>
- Facebook integration - ON without error(s)
- OmniChannel API Key - SUPPLIED without error(s)
- OmniChannel API Secret - SUPPLIED without error(s)
2. Go back to Main Menu
3. Under Main Menu>Omnichannel>Facebook Messenger
- ENABLE
- Link Facebook page in the popup
- YES to all data RocketChat needs
- Toggle Facebook Page to ON

### Expected behavior:
Facebook Page omnichannel livechat toggle stays as ON and livechat continues normally

### Actual behavior:
* Error popout: (#100) The parameter subscribed_fields is required. [integration-error]
* Toggle Facebook Page goes back to OFF
* Log

I20201113-22:20:25.751(0) 
Exception while invoking method livechat:facebook Error: (#100) The parameter subscribed_fields is required. [integration-error]
at MethodInvocation.livechat:facebook (app/livechat/server/methods/facebook.js:56:12)
at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
at packages/ddp-server/livedata_server.js:1689:15
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
at packages/ddp-server/livedata_server.js:1687:36
at new Promise (<anonymous>)
at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
at Server.call (packages/ddp-server/livedata_server.js:1607:17)
at Object.post (app/api/server/v1/misc.js:262:26)
at app/api/server/api.js:394:82
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
at packages/nimble_restivus/lib/route.coffee:59:33
at packages/simple_json-routes.js:98:9  => awaited here:
at Promise.await (/snap/rocketchat-server/1442/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
at Server.call (packages/ddp-server/livedata_server.js:1607:17)
at Object.post (app/api/server/v1/misc.js:262:26)
at app/api/server/api.js:394:82
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
at packages/nimble_restivus/lib/route.coffee:59:33
at packages/simple_json-routes.js:98:9 

### Server Setup Information:
* Version of Rocket.Chat Server: 3.6.2
* Operating System: Ubuntu 18.04
* Deployment Method: Snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* NodeJS Version: v12.16.1
* MongoDB Version: 3.6.14

### Client Setup Information
* Desktop App or Browser Version: Desktop/Chrome 86.0.4240.111
* Operating System: Windows7 & Windows 10

**Comment by renatobecker** [comment]
This issue is supposed to be fixed, please try again.
