### ISSUE TITLE
"Invalid Room" Error when reloading or switching sites 

### ISSUE THREAD

**Issue by Corinari** [RocketChat/Rocket.Chat.Livechat#539]
We see a problem when people are using the ommnichat (from now on called customers, for differentiation) reload/refresh the Website or load a different page on same website, an error occurs where 
1) there is a "invalid Error"- notification on customer side
2) Customer can read/see new replies by the LiveChat agent, but cannot answer them
3) No warning of this error to the Agent itself. 

This is one error message i found in the logs:
`
I20201207-14:32:13.676(0) server.js:204 API ➔ debug Failure {   statusCode: 400,   body: TypeError: Cannot read property '_id' of undefined       at Messages.createNavigationHistoryWithRoomIdMessageAndUser (app/models/server/models/Messages.js:774:15)       at Object.savePageHistory (app/livechat/server/lib/Livechat.js:554:20)       at Object.post (app/livechat/server/api/v1/pageVisited.js:23:25)       at app/api/server/api.js:394:82       at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)       at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)       at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)       at packages/nimble_restivus/lib/route.coffee:59:33       at packages/simple_json-routes.js:98:9 {     success: false   } } 
`

We are still running on RocketChat version 3.7.1, planning to update to 3.9.0 this or next week. 

Thanks for any help, 
Best regards,

**Comment by Corinari** [comment]
Update to 3.9.1 seem to fix it
